language: python
env:
    global:
    jobs:
        - APPS="admin_changelist admin_custom_urls admin_docs admin_inlines admin_ordering aggregation aggregation_regress annotations backends"
        # Commented out because they take longer 2hr and TravisCI unconditionally terminates them.
        # - APPS="auth_tests"
        - APPS="basic bulk_create choices custom_columns cache custom_methods custom_pk datatypes dates datetimes"
        - APPS="defer defer_regress delete_regress db_functions db_utils distinct_on_fields empty expressions expressions_window field_defaults"
        - APPS="field_subclassing file_storage file_uploads fixtures fixtures_model_package from_db_value get_earliest_or_latest get_object_or_404 i18n"
        - APPS="indexes inline_formsets introspection invalid_models_tests known_related_objects lookup max_lengths m2m_and_m2o m2m_intermediary m2m_multiple m2m_recursive"
        - APPS="m2m_regress m2m_signals m2m_through m2m_through_regress m2o_recursive managers_regress many_to_many many_to_one many_to_one_null max_lengths"
        - APPS="migrate_signals migration_test_data_persistence model_fields.test_binaryfield model_fields.test_booleanfield model_fields.test_charfield"
        # Run model_fields piecemeal because running it all at once takes
        # longer then 2 hours (Travis CI limit).
        - APPS="model_fields.test_datetimefield model_fields.test_decimalfield model_fields.test_durationfield model_fields.test_field_flags model_fields.test_filefield"
        - APPS="model_fields.test_floatfield model_fields.test_foreignkey model_fields.test_genericipaddressfield model_fields.test_imagefield model_fields.test_integerfield"
        - APPS="model_fields.test_manytomanyfield model_fields.test_promises model_fields.test_slugfield model_fields.test_textfield model_fields.test_uuid null_fk null_fk_ordering"
        - APPS="null_queries one_to_one or_lookups ordering queries.test_bulk_update queries.test_explain queries.test_iterator queries.test_q queries.test_qs_combinators queries.test_query"
        # Commented out because they take longer 2hr and TravisCI unconditionally terminates them.
        # - APPS="queries.tests"
        - APPS="raw_query redirects_tests reserved_names reverse_lookup save_delete_hooks select_related select_related_onetoone signing sitemaps_tests string_lookup signals"
        - APPS="test_utils test_client test_client_regress timezones transactions unmanaged_models update_only_fields update validation view_tests"

python:
    - "3.7"
script:
    - ./bin/parallelize_tests_linux
